## 生产环境提高 自我保护触发门槛
#eureka.instance.lease-renewal-interval-in-seconds=10
#eureka.server.renewal-percent-threshold=0.49

# 当前服务名
spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  server:
    peer-eureka-nodes-update-interval-ms: 10000 #默认是10分钟即600000，这里为了验证改为10秒