spring:
  application:
    name: feign-provider
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    # 拉取注册信息的频率
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 10 # 默认为300秒，这里为了验证改为10秒

management:
  endpoints:
    web:
      exposure:
        include: '*'